id: IDC8B8D38
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:17:36+00:00'
last_modified: '2022-06-08T12:56:51.194480+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30157
  title: ཀུན་སྤང་ཆོས་ཀྱི་རིན་ཆེན་གྱི་རྣམ་ཐར་རིན་ཆེན་ཕྲེང་བ་དང་རྡོ་དམར་ཞབས་དྲུང་མི་འགྱུར་རྡོ་རྗེའི་ཤུགས་འབྱུང་ཉམས་གླུའི་འཕྲེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    726F:
      image_group_id: I5946
      title: ''
      total_pages: 522
      order: 1
      base_file: 726F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
