id: opecha:P010350
initial_creation_type: ocr
source_metadata:
  id: bdr:W30157
  title: ཀུན་སྤང་ཆོས་ཀྱི་རིན་ཆེན་གྱི་རྣམ་ཐར་རིན་ཆེན་ཕྲེང་བ་དང་རྡོ་དམར་ཞབས་དྲུང་མི་འགྱུར་རྡོ་རྗེའི་ཤུགས་འབྱུང་ཉམས་གླུའི་འཕྲེང་བ།
  volume: ''
  author: ''
